"""defalut count

Revision ID: 5890fbf77225
Revises: 43c21ac58a9d
Create Date: 2018-11-30 12:14:07.683893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5890fbf77225'
down_revision = '43c21ac58a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_count'), 'user', ['count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_count'), table_name='user')
    # ### end Alembic commands ###
